project:
  type: website
  output-dir: docs
  resources:
  - "/demo-files/"
  render:
    - "*.qmd"
    - "!/demo-files"

website:
  title: "SAIL @ UNC"
  favicon: "favicon.html"
  navbar:
    logo: imgs/SAIL LOGO 4-01.png
    logo-alt: "SAIL Logo"
    left:
      - text: "About"
        href: index.qmd
      - text: "Team"
        href: team.qmd
      - text: "Events"
        href: events.qmd
      - text: "Projects"
        href: projects.qmd
      - text: "Apply"
        href: apply.qmd
      - text: "Contact"
        href: contact.qmd
    background: "primary"
    type: "dark"

format:
  html:
    theme: litera
    css: styles.css
    toc: true
    toc-location: right
    number-sections: false
    code-fold: false
    code-tools: false
    code-link: false
    fig-cap-location: margin
    fig-dpi: 300
    fig-format: png
    fig-width: 8
    fig-height: 6
    fig-align: center
    link-external-newwindow: true
    link-external-icon: true
    html-math-method: katex
    include-in-header: header.html
    page-layout: full

editor: visual


