project:
  type: website
  output-dir: docs
  resources:
  - "/demo-files/"
  render:
    - "*.qmd"
    - "!/demo-files"

website:
  title: "SAIL @ UNC"
  favicon: "favicon.html"
  navbar:
    left:
      - href: index.qmd
        text: "About"
      - href: team.qmd
        text: "Team"
      - href: events.qmd
        text: "Events"
      - href: projects.qmd
        text: "Projects"
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
=======
>>>>>>> parent of 5849b82 (Touch Ups)
=======
>>>>>>> parent of 5849b82 (Touch Ups)
=======
>>>>>>> parent of 5849b82 (Touch Ups)
<<<<<<< Updated upstream
      - href: apply.qmd
        text: "Apply"
=======
>>>>>>> Stashed changes
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> parent of 5849b82 (Touch Ups)
=======
>>>>>>> parent of 5849b82 (Touch Ups)
=======
>>>>>>> parent of 5849b82 (Touch Ups)
=======
>>>>>>> parent of 5849b82 (Touch Ups)
      - href: contact.qmd
        text: "Contact"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual


