---
title: "SAIL Projects"
---

**Investigating the Presence of Mechanical Deviations in Baseball Swings Over Time**

*Contributors:* Khushi Shah, Yunus Mouline\
*Links:* [Paper](projects/YaleAnalyticsPaper.pdf)

::: {.callout-note appearance="minimal"}
**Abstract**

<div style="text-align: left;">

In professional baseball, every swing reflects a decision influenced by pitch characteristics, game context, and a batter's intent. However, deviations from expected swing mechanics may indicate a breakdown in consistency throughout a game. This study investigates the presence and progression of deviations from expected swing mechanics throughout a game, focusing on two key metrics: swing length residuals and the relationship between bat speed and launch speed. Using pitch-level data from Major League Baseball, we apply regression models and residual analysis to quantify these deviations. A logistic regression indicated a $26.4\%$ increase in unintended swing likelihood per additional swing in an inning (p \< 0.001). Swing length analysis revealed increasing mechanical variability, with mean squared error increasing significantly with swing count (Estimate: $0.00176$, $p = 0.00467$). These trends suggest a pattern of mechanical inconsistency, potentially linked to fatigue or cognitive strain. This research provides a foundation for further exploration into batter performance trends and offers insights for coaching strategies aimed at injury prevention and fatigue management.

</div>
:::

------------------------------------------------------------------------

**Quantifying the Impact of Current NBA Coaches**

*Contributor:* Shane Faberman\
*Links:* [Paper](projects/coach_research.pdf), [Poster](projects/coach_poster_sep25.pdf)

::: {.callout-note appearance="minimal"}
**Abstract**

In the NBA, coaches play a crucial role in game strategy, player development, and managing team dynamics. However, quantifying coaching impact remains a challenge, as it is difficult to isolate a coach’s influence from that of their players. Unlike the plethora of statistics available for evaluating players, coaching performance is assessed far more subjectively. This study introduces a new metric, Box Plus-Minus (BPM) Over Expected(BOE), that evaluates coaches based on how their players perform relative to expectations, aiming to identify those who consistently maximize their players’ potential. To calculate BOE, Expected BPM (EBPM) was first computed for each player-season. Let a player’s age $n$ season represent the season when they were n years old. EBPM was derived by adjusting a player’s BPM from their age $n-1$ season based on average aging trends for qualifying players and the deviation from the league-average qualifying player at age $n-1$. BOE was then calculated as the difference between a player’s actual BPM in their age $n$ season and their EBPM. According to BOE, media coach rankings tend to overrate championship-winning coaches. This is likely due to underrating the effect of superstar players such as Lebron James, Stephen Curry, and Nikola Jokić. Championships and regular-season win-loss records depend on many factors not under a coach’s control. BOE provides a more nuanced assessment of a coach’s system’s impact by shifting the focus toward individual player performance relative to expectation. It serves as a valuable tool, in conjunction with other factors, for evaluating coaching effectiveness.
:::

------------------------------------------------------------------------

**NFLPA 2024 Case Competition**

*Contributors:* Shane Faberman, Arsh Madhani,Isabel Marshall, Gordan Tao\
*Links:* [Paper](projects/NFLPA%20Write-Up.pdf)

------------------------------------------------------------------------

**Assessment of Cyclical and Derivative-based Acute:Chronic Workload Ratios for Predicting Injuries in Collegiate Men's Basketball**

*Contributors:* Conor Kerr, Doug Halverson, Khushi Shah

------------------------------------------------------------------------

**Utilizing Training Load and Intensity to Predict Team Performance in NCAA Division I Men's Basketball**

*Contributors:* Conor Kerr, Sam Moore, Doug Halverson, Abbie Smith-Ryan\
*Presented:* April 2023
